### PR TITLE
trivy action corrected

### PR DESCRIPTION
**Pull request by zLukas**
Add:
* Upgrade trivy scans
* Increase scans severity in trivy output
* branch parameter to action

### CODE REVIEW

**Review by Mionsz — CHANGES_REQUESTED** [review]
This fix does not work at all.

**Comment by zLukas** [comment]
> This fix does not work at all.

can you be more specific, what is excepted result ?

**Comment by Mionsz** [comment]
You are asking me xD? That is your PR and it does not build on push nor commit and this is mandatory.

**Review by MateuszGrabuszynski — APPROVED** [review]
lgtm

**Review by soopel — APPROVED** [review]
Looks good to me

**Pull request merged**
